#!/bin/bash
CURRENT_DIR=$(pwd)

make_service()
{
cat <<EOF
[Unit]
\rDescription="S1 Panel"
\r
\r[Service]
\rExecStart=/usr/bin/node main.js
\rWorkingDirectory=$CURRENT_DIR
\rRestart=always
\rRestartSec=10
\rSyslogIdentifier=s1panel
\rEnvironment=SERVICE=true
\r
\r[Install]
\rWantedBy=multi-user.target
\r
EOF
}

echo "Home Directory is $CURRENT_DIR"
npm i
(cd gui; npm i)
echo "Building GUI"
(cd gui; npm run build)
echo "Install Service..."
echo -e "$(make_service)" > /etc/systemd/system/s1panel.service
echo "Reload Service Daemon..."
systemctl daemon-reload
echo "Enable s1panel..."
systemctl enable s1panel.service
echo "Start s1panel..."
systemctl start s1panel.service
echo "Done!"
systemctl status s1panel.service
